### ISSUE TITLE
Error: "AppTrackingTransparency" plugin is not implemented on ios

### ISSUE THREAD

**Issue by nowitz** [mahnuh/capacitor-plugin-app-tracking-transparency#12]
# Bug Report

**Plugin version:**
[ ] **1.x**
[x] **2.0.3**

**Capacitor version:**
[ ] **2.x**
[] **3.x**
[x] **4.0.1**

**Current behavior:**
After I added this plugin and run app I have this exception in log

`[error] - ERROR Error: Uncaught (in promise): Error: "AppTrackingTransparency" plugin is not implemented on ios
te@capacitor://localhost/main.b7d4641eaa6e5c9d.js:1:10040
@capacitor://localhost/main.b7d4641eaa6e5c9d.js:1:11592
@capacitor://localhost/main.b7d4641eaa6e5c9d.js:1:11892
onInvoke@capacitor://localhost/main.b7d4641eaa6e5c9d.js:1:318462
@capacitor://localhost/polyfills.3ebd5e0cff18d293.js:1:2768
@capacitor://localhost/polyfills.3ebd5e0cff18d293.js:1:18559
onInvokeTask@capacitor://localhost/main.b7d4641eaa6e5c9d.js:1:318282
@capacitor://localhost/polyfills.3ebd5e0cff18d293.js:1:3437
A@capacitor://localhost/polyfills.3ebd5e0cff18d293.js:1:10761
@capacitor://localhost/polyfills.3ebd5e0cff18d293.js:1:9532`

**Expected behavior:**
Plugin will work.

**Steps to reproduce:**
Add the plugin to app.

**Related code:**

<img width="675" alt="Snímek obrazovky 2022-09-14 v 9 06 47" src="https://user-images.githubusercontent.com/12040747/190084899-39ce1a19-eecf-41b1-b467-3c0213a635c9.png">
<img width="920" alt="Snímek obrazovky 2022-09-14 v 9 05 58" src="https://user-images.githubusercontent.com/12040747/190084889-f953d6c9-1a01-4e2c-9d61-4e8b5c9dd544.png">

**Ionic info:**
Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.2
   @angular-devkit/build-angular : 14.1.2
   @angular-devkit/schematics    : 14.1.2
   @angular/cli                  : 14.1.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.0) : 1.6.0

System:

   NodeJS : v16.16.0 (/usr/local/bin/node)
   npm    : 8.17.0
   OS     : macOS Monterey

**Comment by mahnuh** [comment]
Hi @nowitz please provide an example repository where the error is reproducible, as I am not able to.

**Comment by mahnuh** [comment]
Closing this for now as not reproducible.
