### ISSUE TITLE
Problem with show confirm dialog "Asking Permission to Track" for  iOS 16.1

### ISSUE THREAD

**Issue by nowitz** [mahnuh/capacitor-plugin-app-tracking-transparency#14]
# Bug Report
The plugin worked good with iOS version < 16.0, bud then I install my app on device with iOS 16.1, the confirm dialog "Asking Permission to Track" did not show.

**Plugin version:**
[x] **2.0.3**

**Capacitor version:**
[x] **4.2.0**

**Current behavior:**
Confirm dialog "Asking Permission to Track" did not show.

**Expected behavior:**
Confirm dialog"Asking Permission to Track" will show.
![image](https://user-images.githubusercontent.com/12040747/199185528-583856db-9ae8-4eef-839d-fbb51499b04c.png)

**Related code:**
I have the code as shown (readme).
https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency/blob/main/README.md

**Other information:**
Response from Apple review:

> Guideline 2.1 - Information Needed
> 
> 
> We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 16.1.
> 
> 
> Next Steps
> 
> 
> Please explain where we can find the App Tracking Transparency permission request in your app. The request should appear before any data is collected that could be used to track the user.
> 
> 
> If you've implemented App Tracking Transparency but the permission request is not appearing on devices running the latest OS, please review the [available documentation](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorization) and confirm App Tracking Transparency has been correctly implemented.
> 
> 
> If your app does not track users, update your [app privacy information in App Store Connect](https://help.apple.com/app-store-connect/#/dev1b4647c5b) to not declare tracking. You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.
> 
> 
> Resources
> 
> 
> - Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about [tracking](https://developer.apple.com/app-store/app-privacy-details/#user-tracking).
> 
> - See Frequently Asked Questions about the [requirements for apps that track users](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).
> 
> - Review developer documentation for [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency).

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.7
   @angular-devkit/build-angular : 14.2.2
   @angular-devkit/schematics    : 14.2.2
   @angular/cli                  : 14.2.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.2.0
   @capacitor/ios     : 4.2.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.16.0 (/usr/local/bin/node)
   npm    : 8.17.0
   OS     : macOS Monterey
```

**Comment by mahnuh** [comment]
Thanks for reporting @nowitz, will be looking into it today.

**Comment by mahnuh** [comment]
In the meantime, could you check if this demo app (https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency-demo-app) has the same issue on iOS 16.1 @nowitz? I have to update macOS and Xcode frist, which might take a while...

**Comment by nowitz** [comment]
I tried your @mahnuh  demo and it has the same problem. :-/

**Comment by mahnuh** [comment]
I am not able to reproduce this issue, works fine with the demo app, tested on simulator and iPhone, both iOS 16.1.
@nowitz can you please provide the log output for the demo app from Xcode? See mine below. I first tapped the GET STATUS button, then REQUEST PERMISSIN and allowed tracking.

<img width="765" alt="Screenshot 2022-11-01 at 12 39 08" src="https://user-images.githubusercontent.com/978226/199225021-ebe7d73e-634c-4b7d-9de4-5593c2768042.png">

**Comment by nowitz** [comment]
For emulator iphone 14 pro is everything ok. I have the same log how you. 
But this is log on real device iphone 11 pro.
<img width="579" alt="Snímek obrazovky 2022-11-01 v 14 07 20" src="https://user-images.githubusercontent.com/12040747/199240661-74927325-daeb-4e40-933e-8174c0eda1f1.png">

**Comment by mahnuh** [comment]
That looks right an denied in this case means that you have denied tracking system wide. Please check the privacy settings on your iPhone @nowitz.

**Comment by nowitz** [comment]
Ok I found it a it work ok. But then i don't know what apple means report from release review :-/
> Guideline 2.1 - Information Needed
> 
> 
> We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 16.1.
> 
> 
> Next Steps
> 
> 
> Please explain where we can find the App Tracking Transparency permission request in your app. The request should appear before any data is collected that could be used to track the user.
> 
> 
> If you've implemented App Tracking Transparency but the permission request is not appearing on devices running the latest OS, please review the [available documentation](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorization) and confirm App Tracking Transparency has been correctly implemented.
> 
> 
> If your app does not track users, update your [app privacy information in App Store Connect](https://help.apple.com/app-store-connect/#/dev1b4647c5b) to not declare tracking. You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.
> 
> 
> Resources
> 
> 
> - Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about [tracking](https://developer.apple.com/app-store/app-privacy-details/#user-tracking).
> 
> - See Frequently Asked Questions about the [requirements for apps that track users](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).
> 
> - Review developer documentation for [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency).

**Comment by mahnuh** [comment]
Settings > Privacy & Security > Tracking

**Comment by nowitz** [comment]
👍 Ok I found it a it work ok. @mahnuh 
 👎  But then i don't know what apple means report from release review? 
> Guideline 2.1 - Information Needed
> 
> 
> We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 16.1.
> 
> 
> Next Steps
> 
> 
> Please explain where we can find the App Tracking Transparency permission request in your app. The request should appear before any data is collected that could be used to track the user.
> 
> 
> If you've implemented App Tracking Transparency but the permission request is not appearing on devices running the latest OS, please review the [available documentation](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorization) and confirm App Tracking Transparency has been correctly implemented.
> 
> 
> If your app does not track users, update your [app privacy information in App Store Connect](https://help.apple.com/app-store-connect/#/dev1b4647c5b) to not declare tracking. You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.
> 
> 
> Resources
> 
> 
> - Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about [tracking](https://developer.apple.com/app-store/app-privacy-details/#user-tracking).
> 
> - See Frequently Asked Questions about the [requirements for apps that track users](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).
> 
> - Review developer documentation for [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency).

**Comment by mahnuh** [comment]
Does it work with your app as well? I can only recommend to make a video of the working request in your app and provide it to the Apple review team.

**Comment by nowitz** [comment]
Yes, after enable tracking everything ok in my app. Thank you for your time and I will try some create video for apple. 
I'm guessing that Apple has tracking enabled during testing.
