### ISSUE TITLE
Not getting status on permission clicked, received status before the click.

### ISSUE THREAD

**Issue by vipinsaini0** [mahnuh/capacitor-plugin-app-tracking-transparency#18]
# Bug Report

**Plugin version:**
[ ] **1.x**
[x] **2.x**

**Capacitor version:**
[ ] **2.x**
[x] **3.x**

**Current behavior:**

the following getting before click any option
⚡️  TO JS {"status":"denied","value":"00000000-0000-0000-0000-000000000000"}
⚡️  TO JS {"status":"unrequested","value":"00000000-0000-0000-0000-000000000000"}

and on click no status received.

**Expected behavior:**

On click option, allow or not allow at that movement need to receive status, so according to that we can handle other process

**Steps to reproduce:**

once show default alert just wait 10 second and click any option, nothing receive.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by mahnuh** [comment]
Please provide a repository where the issue is reproducible. Otherwise I won't be able to help.

**Comment by vipinsaini0** [comment]
https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency

**Comment by mahnuh** [comment]
I need a repo where you use this plugin and where I can reproduce the issue, not a link to the plugin repo...

**Comment by vipinsaini0** [comment]
```
import {
  AppTrackingTransparency,
  AppTrackingStatusResponse,
} from 'capacitor-plugin-app-tracking-transparency';

...

public async getStatus(): Promise<AppTrackingStatusResponse> {
  const response = await AppTrackingTransparency.getStatus();

  console.log(response);
  // { status: 'authorized' } for example

  return response;
}

public async requestPermission(): Promise<AppTrackingStatusResponse> {
  const response = await AppTrackingTransparency.requestPermission();

  console.log(response);
  // { status: 'authorized' } for example

  return response;
}





```






the same code I copy-paste but not work as expected. On the first run direct getting following: 
```
⚡️ TO JS {"status":"denied","value":"00000000-0000-0000-0000-000000000000"}
⚡️ TO JS {"status":"unrequested","value":"00000000-0000-0000-0000-000000000000"}
```

and on permission alert's option click, nothing happened.

**Comment by mahnuh** [comment]
Again, I need a complete repository to help you. And more information about your setup. Capacitor version?
Check out this repo and verify if it is working there: https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency-demo-app

**Comment by mahnuh** [comment]
I updated the demo app mentioned above to Capacitor 6 and everything still works. If you can not provide a repo then I will not be able to help you.

**Comment by vipinsaini0** [comment]
Please check this repo-  https://github.com/vipinsaini0/app-tracking-transparency

I'm still facing same issue. before click on Allow or not it's giving status and after clicking on any option not status receiving.

![Screenshot 2024-05-08 at 10 00 30 AM](https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency/assets/16730481/d8b97929-669c-476a-8197-444d86050f0a)

**Comment by altaidyn00** [comment]
@mahnuh Exactly the same issue I faced yesterday. Initially requestPermission method return status 'denied' before choosing one of the options Allow/Ask App Not to Track, but even after choosing it doesn't return status
