### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by gasci** [mahnuh/capacitor-plugin-app-tracking-transparency#19]
Android SDK 34+ will be mandatory after August 2024. Do you have plans to upgrade this plugin?

**Comment by mahnuh** [comment]
Not sure what the problem is here, can you please elaborate?
This is an iOS only plugin, so the Android SDK level does not matter.

**Comment by gasci** [comment]
If there is a capacitor core version dependency, it should be updated to >6.0.0. If not, there shouldn't be a problem. Because everybody will be forced to upgrade to capacitor 6.0.0 soon.

**Comment by mahnuh** [comment]
It does not and works fine with Capacitor 6, as can be seen here: https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency-demo-app
