### ISSUE TITLE
Aligning the plugin version with the capacitor version

### ISSUE THREAD

**Issue by gasci** [mahnuh/capacitor-plugin-app-tracking-transparency#20]
Is it possible to align the release version with the capacitor version; e.g. `6.0.0`?

**Comment by mahnuh** [comment]
Why would we need this?

**Comment by gasci** [comment]
It is not crucial but more convenient. Additionally, you won't need to maintain the capacitor version table on the README file. The plugin version will reveal the capacitor version compability. This is the case with most of the community plugins. I created the same version issue for other plugins, too.

This plugin recently aligned its version, too.
https://github.com/calvinckho/capacitor-jitsi-meet

<img width="411" alt="Screenshot 2024-04-29 at 13 29 01" src="https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency/assets/29505701/f6946826-9e1f-4878-865a-988da472b59a">
